server:
  mode: debug
  host: 0.0.0.0
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: ""
  dbname: hermes
  sslmode: disable

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
